[package]
name = "control-plane"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
axum.workspace = true
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
reqwest.workspace = true
uuid.workspace = true
regex.workspace = true
chrono.workspace = true
aws-config.workspace = true
aws-sdk-s3.workspace = true
base64 = "0.22"
async-trait = "0.1"
jsonwebtoken = "9"

[dev-dependencies]
http-body-util = "0.1"
tower = "0.5"
